# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-22 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='picture',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
