# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-01 18:01
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='recommendation',
        ),
        migrations.AddField(
            model_name='link',
            name='places',
            field=models.ManyToManyField(through='cities.Recommendation', to='cities.Place'),
        ),
        migrations.AddField(
            model_name='place',
            name='types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=[], size=None),
        ),
        migrations.AddField(
            model_name='recommendation',
            name='place',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='cities.Place'),
            preserve_default=False,
        ),
    ]
