# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-22 17:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0002_user_data_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_data',
            name='picture',
        ),
    ]
